analytics:
  google:
    id: UA-33449675-2

repository: https://github.com/iROCKBUNNY/iRB-Story

timezone: Asia/Shanghai
lang: zh_CN

title: 生活 · 读书 · 新知
description: iROCKBUNNY Story
keywords: iROCKBUNNY, Story, Blog, 生活, 读书, 新知, 博客, 睡前故事
url: http://story.irockbunny.com

author: iROCKBUNNY
author_url: http://irockbunny.com
organization: TEELAB
organization_url: http://teelab.net

contact: contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
avatar: /images/avatar.jpg

permalink: /article/:year/:month/:day/:title

paginate: 5
paginate_path: /articles/:num/

plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE.md
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor